/**
 * ============================================================================
 * InSight Survey Comparison Dashboard
 * ============================================================================
 * Champlain College Career Collaborative
 *
 * This React app visualizes Likert-scale survey data from the InSight program.
 * It shows side-by-side histograms of response distributions across cohorts,
 * overlays curve fits (Gaussian or KDE), and provides a mean score comparison.
 *
 * HOW TO UPDATE DATA:
 * -------------------
 * Data is loaded from src/data.json, generated by the build-data.js script.
 *
 *   1. Drop new Canvas CSV exports into the Kickoff/ or Exit/ folders
 *   2. Run: node build-data.js
 *   3. The app hot-reloads automatically
 *
 * Each dataset in data.json has this shape:
 *
 *   {
 *     "name": "Exit - Class of 2027",     // Display label in charts
 *     "type": "Exit",                      // "Kickoff" or "Exit" (drives aggregation)
 *     "cohort": "Class of 2027",           // Section label from Canvas
 *     "n": 250,                            // Total respondents
 *     "questions": {
 *       "Identify personal values": {
 *         "Very untrue of me": 3,
 *         "Somewhat untrue of me": 8,
 *         "Neutral": 20,
 *         "Somewhat true of me": 95,
 *         "Very true of me": 124
 *       },
 *       // ... all 20 questions with their 5 Likert counts
 *     }
 *   }
 *
 * See README.md for full documentation.
 *
 * DEPENDENCIES:
 * - react (included with create-react-app)
 * - recharts (npm install recharts)
 * ============================================================================
 */

import { useState, useMemo, useRef, useEffect } from "react";
import {
  BarChart,          // The main chart component for bar charts
  Bar,               // Individual bar series
  XAxis, YAxis,      // Axis components
  Tooltip,           // Hover tooltip
  Legend,             // Chart legend
  ResponsiveContainer, // Makes charts responsive to container width
  Cell,              // Lets us color individual bar cells differently
} from "recharts";


// =============================================================================
// DATA
// =============================================================================
// Survey data is loaded from src/data.json, which is generated by build-data.js.
//
// To update the data:
//   1. Drop new Canvas CSV exports into the Kickoff/ or Exit/ folders
//   2. Run: node build-data.js
//   3. The app hot-reloads automatically (if npm start is running)
//
// See README.md for the full workflow.

import DATA from "./data.json";


// =============================================================================
// CONSTANTS
// =============================================================================

// Short labels for the x-axis tick marks (-2 through +2)
const LIKERT_SHORT = ["-2", "-1", "0", "+1", "+2"];

// Numeric values corresponding to each Likert response
const LIKERT_NUMERIC = [-2, -1, 0, 1, 2];

// Diverging color scale for Likert values (red=negative, gray=neutral, green/blue=positive)
const LIKERT_COLORS = ["#b91c1c", "#f97316", "#a3a3a3", "#3b82f6", "#15803d"];

// 10 default colors, chosen to be distinguishable on white backgrounds.
// First 10 datasets get these in order. Overflow datasets get random colors.
const DEFAULT_PALETTE = [
  "#6366f1", // indigo
  "#0ea5e9", // sky
  "#f59e0b", // amber
  "#10b981", // emerald
  "#ef4444", // red
  "#8b5cf6", // violet
  "#ec4899", // pink
  "#14b8a6", // teal
  "#f97316", // orange
  "#6b7280", // gray
];

// Default colors for aggregate datasets (All Kickoffs, All Exits)
const AGG_DEFAULTS = {
  "All Kickoffs Combined": "#8b5cf6",
  "All Exits Combined": "#ef4444",
};

// ~20 curated swatch options for the color picker
const COLOR_SWATCHES = [
  "#ef4444", "#f97316", "#f59e0b", "#eab308",
  "#84cc16", "#22c55e", "#10b981", "#14b8a6",
  "#06b6d4", "#0ea5e9", "#3b82f6", "#6366f1",
  "#8b5cf6", "#a855f7", "#d946ef", "#ec4899",
  "#f43f5e", "#78716c", "#6b7280", "#1e293b",
];

/**
 * Convert a hex color to a light tinted version (for button backgrounds).
 * Works by mixing the color with white at ~90% white.
 */
function hexToLight(hex) {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  // Mix with white (255) at 85% white
  const lr = Math.round(r + (255 - r) * 0.85);
  const lg = Math.round(g + (255 - g) * 0.85);
  const lb = Math.round(b + (255 - b) * 0.85);
  return `rgb(${lr}, ${lg}, ${lb})`;
}

/**
 * Generate a random color that has enough contrast against existing colors.
 * Uses HSL to ensure vivid, distinguishable hues.
 */
function generateOverflowColor(existingColors, index) {
  // Golden angle hue spacing starting from a high offset to avoid clashing with defaults
  const hue = (index * 137.508 + 200) % 360;
  return `hsl(${Math.round(hue)}, 65%, 50%)`;
}

// Full question text from the Canvas survey, mapped by the short label.
// Shown on hover over the chart title so the abbreviated label doesn't lose context.
const FULL_QUESTIONS = {
  "Identify personal values": "I am able to clearly identify my personal values.",
  "Ask for help when needed": "I am able to ask for help when I need it.",
  "Help others through difficult situations": "I feel confident helping others through difficult situations.",
  "Recognize when I need help": "I recognize when I need help.",
  "Reflect on what's important in life": "I take time to think about what's important in life \u2014 who I am, what I value, where I fit in, and where I'm going.",
  "Goals for work/life integration": "I have clearly defined goals related to positive work/life integration (balancing personal and professional time).",
  "Follow a financial plan": "If I had a goal for my future that involved a financial commitment, I would feel comfortable following a plan to achieve that goal.",
  "Build and manage a monthly budget": "I feel confident building and managing a monthly budget.",
  "Working knowledge of credit": "I have a working knowledge of credit (credit cards, credit report, credit score).",
  "Follow through with a savings plan": "I feel confident in following through with a savings plan.",
  "Research cost of living": "I know how to research the cost of living and its impacts on my budget.",
  "Negotiate salary": "I would feel confident negotiating my salary when offered a future job.",
  "Resume confidence": "I have a resume that I would feel confident using in a job application tomorrow.",
  "LinkedIn profile": "I have a LinkedIn Profile that accurately reflects my experience and professional interests.",
  "Write a cover letter": "I feel confident writing a cover letter for a job that interests me.",
  "Attend a networking event": "I feel confident attending a networking event (this could be a career fair or social gathering aimed at professional advancement).",
  "Elevator pitch": "I know how to speak about my professional interests and personal strengths when meeting with a potential employer (elevator pitch).",
  "Plan to pay off debts": "I have a plan to pay off my debts (student loans, credit card balances, personal loans from family/friends, etc.) If I don't have debts today, I would be able to create a plan to pay off any future debts I may incur.",
  "Job interview confidence": "Even though I may have some nerves or anxiety, I feel confident in my ability to have a job interview where I feel I've presented myself to the best of my ability.",
  "Ready to launch career": "I feel ready to launch my career.",
};

// The 20 questions grouped into three InSight program pillars.
// Used by the Category view to show aggregate scores per domain.
const QUESTION_CATEGORIES = {
  "Wellbeing": [
    "Identify personal values",
    "Ask for help when needed",
    "Help others through difficult situations",
    "Recognize when I need help",
    "Reflect on what's important in life",
    "Goals for work/life integration",
  ],
  "Financial Literacy": [
    "Follow a financial plan",
    "Build and manage a monthly budget",
    "Working knowledge of credit",
    "Follow through with a savings plan",
    "Research cost of living",
    "Negotiate salary",
    "Plan to pay off debts",
  ],
  "Career Positioning": [
    "Resume confidence",
    "LinkedIn profile",
    "Write a cover letter",
    "Attend a networking event",
    "Elevator pitch",
    "Job interview confidence",
    "Ready to launch career",
  ],
};

const CATEGORY_COLORS = {
  "Wellbeing": "#8b5cf6",
  "Financial Literacy": "#10b981",
  "Career Positioning": "#0ea5e9",
};


// =============================================================================
// AGGREGATE DATASET BUILDER
// =============================================================================
// Combines all Kickoff datasets into one and all Exit datasets into one.
// The aggregation sums raw response counts, so percentages are naturally
// weighted by sample size (larger cohorts contribute more, as they should).

function buildAggregates() {
  // Group datasets by their type field
  const groups = { Kickoff: [], Exit: [] };
  DATA.datasets.forEach(ds => {
    if (groups[ds.type]) groups[ds.type].push(ds);
  });

  // For each type that has data, sum counts across all datasets
  return Object.entries(groups)
    .filter(([, list]) => list.length > 0)
    .map(([type, list]) => {
      const questions = {};
      DATA.questions.forEach(q => {
        questions[q] = {};
        DATA.likertScale.forEach(likert => {
          // Sum this Likert response across all datasets of this type
          questions[q][likert] = list.reduce(
            (sum, ds) => sum + (ds.questions[q]?.[likert] || 0), 0
          );
        });
      });
      return {
        name: `All ${type}s Combined`,
        type,
        cohort: `All ${type}s`,
        n: list.reduce((sum, ds) => sum + ds.n, 0),
        questions,
      };
    });
}

const AGGREGATE_DATASETS = buildAggregates();


// =============================================================================
// STATISTICS & CURVE FIT FUNCTIONS
// =============================================================================

/**
 * Compute mean, standard deviation, and total from a question's Likert counts.
 * This is the foundation for all three fit methods.
 *
 * @param {Object} counts - e.g. {"Very untrue of me": 10, "Neutral": 30, ...}
 * @returns {{ mean: number, std: number, total: number }}
 */
function computeStats(counts) {
  const total = Object.values(counts).reduce((a, b) => a + b, 0);
  if (total === 0) return { mean: 0, std: 1, total: 0 };

  // Weighted mean: Σ(value × count) / total
  let sum = 0, sumSq = 0;
  DATA.likertScale.forEach((label, i) => {
    const val = LIKERT_NUMERIC[i];
    const c = counts[label] || 0;
    sum += val * c;
    sumSq += val * val * c;
  });
  const mean = sum / total;

  // Variance: E[X²] - (E[X])², floored at 0.01 to avoid division by zero
  const variance = Math.max(sumSq / total - mean * mean, 0.01);
  return { mean, std: Math.sqrt(variance), total };
}

/**
 * Standard Gaussian (normal distribution) probability density function.
 * Used by Method of Moments and Least Squares fits.
 *
 * @param {number} x - Point to evaluate
 * @param {number} mean - Distribution mean (μ)
 * @param {number} std - Distribution standard deviation (σ)
 * @returns {number} PDF value at x
 */
function gaussianPDF(x, mean, std) {
  const s = Math.max(std, 0.05); // floor to prevent division by zero
  return (1 / (s * Math.sqrt(2 * Math.PI))) * Math.exp(-0.5 * ((x - mean) / s) ** 2);
}


// -----------------------------------------------------------------------------
// FIT METHOD 1: Method of Moments (MoM)
// -----------------------------------------------------------------------------
// The simplest approach: compute mean and std directly from the data,
// then evaluate the normal PDF with those parameters.
//
// Pros: instant to compute, produces clean μ and σ for reporting
// Cons: assumes symmetry, can't capture skew (e.g. LinkedIn profile kickoff)

/**
 * @param {Object} counts - Likert response counts
 * @param {number[]} xCurve - Array of x values to evaluate (e.g. -2.8 to 2.8)
 * @returns {{ y: number[], annotation: string }}
 */
function fitMethodOfMoments(counts, xCurve, usePercent = true) {
  const { mean, std, total } = computeStats(counts);
  if (total === 0) return { y: xCurve.map(() => 0), annotation: "" };

  // Scale: PDF × 100 for %, PDF × total for raw counts
  const scale = usePercent ? 100 : total;
  const y = xCurve.map(x => gaussianPDF(x, mean, std) * scale);
  return { y, annotation: `\u03BC=${mean.toFixed(2)}, \u03C3=${std.toFixed(2)}` };
}


// -----------------------------------------------------------------------------
// FIT METHOD 2: Least Squares Gaussian Fit
// -----------------------------------------------------------------------------
// Finds the amplitude, mean, and std that minimize the squared error between
// the Gaussian curve and the 5 observed percentage bars.
//
// Uses a grid search over (μ, σ) with the optimal amplitude solved
// analytically for each pair. With only 5 data points and 2 shape parameters,
// a grid search is fast and guaranteed to find the global optimum, unlike
// gradient descent which can get stuck on skewed distributions.
//
// Pros: hugs the actual bar heights more closely than MoM
// Cons: still forces symmetry (it's a Gaussian), slightly more computation

function fitLeastSquares(counts, xCurve, usePercent = true) {
  const total = Object.values(counts).reduce((a, b) => a + b, 0);
  if (total === 0) return { y: xCurve.map(() => 0), annotation: "" };

  // Observed bar heights at the 5 Likert positions (in whatever scale the bars use)
  const scale = usePercent ? 100 : total;
  const observed = DATA.likertScale.map(
    label => ((counts[label] || 0) / total) * scale
  );

  // Grid search: try many (mu, sigma) combinations.
  // For each pair, the optimal amplitude can be solved in closed form:
  //   amp = Σ(observed_i * g_i) / Σ(g_i^2)
  // where g_i = gaussianPDF(x_i, mu, sigma)
  let bestMu = 0, bestSigma = 1, bestAmp = 1, bestError = Infinity;

  // Search mu from -2.5 to 2.5 in steps of 0.1, sigma from 0.2 to 3.0 in steps of 0.1
  for (let mu = -2.5; mu <= 2.5; mu += 0.1) {
    for (let sigma = 0.2; sigma <= 3.0; sigma += 0.1) {
      // Evaluate Gaussian at the 5 Likert positions
      let sumOG = 0; // Σ(observed * gaussian)
      let sumGG = 0; // Σ(gaussian^2)
      for (let i = 0; i < 5; i++) {
        const g = gaussianPDF(LIKERT_NUMERIC[i], mu, sigma);
        sumOG += observed[i] * g;
        sumGG += g * g;
      }

      // Optimal amplitude (least squares closed-form solution)
      if (sumGG < 1e-10) continue; // degenerate case
      const amp = Math.max(sumOG / sumGG, 0);

      // Compute total squared error for this (mu, sigma, amp)
      let sse = 0;
      for (let i = 0; i < 5; i++) {
        const predicted = amp * gaussianPDF(LIKERT_NUMERIC[i], mu, sigma);
        sse += (predicted - observed[i]) ** 2;
      }

      if (sse < bestError) {
        bestError = sse;
        bestMu = mu;
        bestSigma = sigma;
        bestAmp = amp;
      }
    }
  }

  const y = xCurve.map(x => bestAmp * gaussianPDF(x, bestMu, bestSigma));
  return { y, annotation: `\u03BC=${bestMu.toFixed(2)}, \u03C3=${bestSigma.toFixed(2)}` };
}


// -----------------------------------------------------------------------------
// FIT METHOD 3: Kernel Density Estimation (KDE)
// -----------------------------------------------------------------------------
// Nonparametric: places a small Gaussian "kernel" at every data point and
// sums them to get a smooth density estimate. Captures skew, bimodality,
// and any shape the data actually has.
//
// Since our data is discrete (5 Likert values), we expand the counts into
// individual observations and apply Silverman's bandwidth rule.
//
// Pros: faithful to the actual data shape, no symmetry assumption
// Cons: can look bumpy, no clean μ/σ to report

function fitKDE(counts, xCurve, minBandwidth = 0.7, usePercent = true) {
  const total = Object.values(counts).reduce((a, b) => a + b, 0);
  if (total === 0) return { y: xCurve.map(() => 0), annotation: "" };

  // Expand counts into a raw data array
  // e.g. if "Neutral" has count 30, we add thirty 0s to the array
  const raw = [];
  DATA.likertScale.forEach((label, i) => {
    const count = counts[label] || 0;
    for (let j = 0; j < count; j++) raw.push(LIKERT_NUMERIC[i]);
  });

  if (raw.length < 2) return { y: xCurve.map(() => 0), annotation: "n/a" };

  // Compute standard deviation of the raw data
  const n = raw.length;
  const mean = raw.reduce((a, b) => a + b, 0) / n;
  const variance = raw.reduce((a, b) => a + (b - mean) ** 2, 0) / n;
  const std = Math.sqrt(Math.max(variance, 0.01));

  // Silverman's rule of thumb for bandwidth selection:
  // h = 0.9 * min(std, IQR/1.34) * n^(-1/5)
  //
  // For discrete Likert data with spacing of 1.0 between values, Silverman's
  // rule often picks a bandwidth smaller than the gap, which creates separate
  // peaks at each Likert value (multimodal bumps). Flooring at 0.7 ensures
  // adjacent kernels merge into a single smooth peak while still capturing
  // skew and asymmetry. Increase this value for smoother curves, decrease
  // for more sensitivity to the individual bar heights.
  const bandwidth = Math.max(0.9 * std * Math.pow(n, -0.2), minBandwidth);

  // Evaluate KDE: sum of Gaussian kernels centered at each data point
  const scale = usePercent ? 100 : total;
  const y = xCurve.map(x => {
    let density = 0;
    for (let k = 0; k < n; k++) {
      density += gaussianPDF(x, raw[k], bandwidth);
    }
    // Normalize to density, then scale to match bar heights (% or count)
    return (density / n) * scale;
  });

  return { y, annotation: `\u03BC=${mean.toFixed(2)}, bw=${bandwidth.toFixed(2)}` };
}

/**
 * Registry of all fit methods. Used by the UI toggle and the chart components.
 * To add a new fit method, implement the function and add it here.
 */
const FIT_METHODS = {
  mom:  { fn: fitMethodOfMoments, label: "Method of Moments" },
  lsq:  { fn: fitLeastSquares,    label: "Least Squares" },
  kde:  { fn: fitKDE,             label: "KDE" },
  none: { fn: null,               label: "None" },
};


/**
 * Compute Silverman's and Scott's rule bandwidth for a given Likert count distribution.
 *
 * Silverman's rule: h = 0.9 * min(σ, IQR/1.34) * n^(-1/5)
 * Scott's rule:     h = 3.49 * σ * n^(-1/3)
 *
 * Both are designed for continuous data, so they tend to undersmooth our discrete
 * 5-point Likert data, which is why we need the bandwidth floor slider.
 *
 * @param {Object} counts - Likert response counts
 * @returns {{ silverman: number, scott: number } | null}
 */
function computeBandwidthRules(counts) {
  // Expand to raw data
  const raw = [];
  DATA.likertScale.forEach((label, i) => {
    const c = counts[label] || 0;
    for (let j = 0; j < c; j++) raw.push(LIKERT_NUMERIC[i]);
  });
  const n = raw.length;
  if (n < 2) return null;

  const mean = raw.reduce((a, b) => a + b, 0) / n;
  const std = Math.sqrt(raw.reduce((a, b) => a + (b - mean) ** 2, 0) / n);

  // IQR: sort and pick 25th/75th percentile
  const sorted = [...raw].sort((a, b) => a - b);
  const q1 = sorted[Math.floor(n * 0.25)];
  const q3 = sorted[Math.floor(n * 0.75)];
  const iqr = q3 - q1;

  // Silverman: 0.9 * min(std, IQR/1.34) * n^(-1/5)
  const silverman = 0.9 * Math.min(std, (iqr || std) / 1.34) * Math.pow(n, -0.2);

  // Scott: 3.49 * std * n^(-1/3)
  const scott = 3.49 * std * Math.pow(n, -1 / 3);

  return { silverman, scott };
}


// =============================================================================
// CURVE OVERLAY APPROACH
// =============================================================================
// Instead of using recharts' <Customized> component (which passes internal axis
// data as props, but behaves differently across recharts versions), we draw
// the curve fit as an absolutely-positioned SVG on top of the chart container.
//
// We use a ResizeObserver to track the container width, then compute bar center
// pixel positions from the known chart margins and the fact that recharts
// distributes 5 categorical bars evenly across the plot area.
//
// This approach is version-independent and works in any React + recharts setup.

// Approximate chart layout constants (in pixels).
// These must match the BarChart margin prop and typical recharts axis rendering.
// If your bars look misaligned with the curves, tweak these values.
const CHART_MARGIN = { top: 4, right: 8, bottom: 22, left: 38 };
const CHART_HEIGHT = 190; // matches the ResponsiveContainer height


// =============================================================================
// INFO TOOLTIP COMPONENT
// =============================================================================
// Reusable hover tooltip used throughout the dashboard: curve fit buttons,
// bandwidth anchors, and question titles. Shows a styled popup above the
// wrapped element on hover.

function InfoTooltip({ text, children, width = 260, position = "above" }) {
  const [show, setShow] = useState(false);
  const triggerRef = useRef(null);
  const [coords, setCoords] = useState({ top: 0, left: 0 });
  const isBelow = position === "below";

  // Recalculate position when showing, using the trigger's bounding rect.
  // position: fixed escapes all parent overflow/clipping contexts.
  useEffect(() => {
    if (show && triggerRef.current) {
      const rect = triggerRef.current.getBoundingClientRect();
      setCoords({
        left: rect.left + rect.width / 2,
        top: isBelow ? rect.bottom + 8 : rect.top - 8,
      });
    }
  }, [show, isBelow]);

  return (
    <div
      ref={triggerRef}
      style={{ position: "relative", display: "inline-block" }}
      onMouseEnter={() => setShow(true)}
      onMouseLeave={() => setShow(false)}
    >
      {children}
      {show && (
        <div style={{
          position: "fixed",
          top: isBelow ? coords.top : "auto",
          bottom: isBelow ? "auto" : `calc(100vh - ${coords.top}px)`,
          left: coords.left,
          transform: "translateX(-50%)",
          width,
          padding: "10px 12px",
          background: "#1e1e2e",
          color: "#e0e0e0",
          fontSize: 11,
          lineHeight: 1.5,
          borderRadius: 8,
          boxShadow: "0 4px 20px rgba(0,0,0,0.25)",
          zIndex: 1000,
          pointerEvents: "none",
        }}>
          {text}
          <div style={{
            position: "absolute",
            ...(isBelow
              ? { bottom: "100%", borderBottom: "6px solid #1e1e2e", borderTop: "none" }
              : { top: "100%", borderTop: "6px solid #1e1e2e", borderBottom: "none" }
            ),
            left: "50%",
            transform: "translateX(-50%)",
            width: 0, height: 0,
            borderLeft: "6px solid transparent",
            borderRight: "6px solid transparent",
          }} />
        </div>
      )}
    </div>
  );
}


// =============================================================================
// COLOR PICKER COMPONENT
// =============================================================================
// A small popover with ~20 color swatches. Click the trigger (a colored square)
// to open, click a swatch to apply, click outside or the trigger again to close.

function ColorPicker({ currentColor, onSelect }) {
  const [open, setOpen] = useState(false);
  const ref = useRef(null);

  // Close on outside click
  useEffect(() => {
    if (!open) return;
    const handleClick = (e) => {
      if (ref.current && !ref.current.contains(e.target)) setOpen(false);
    };
    document.addEventListener("mousedown", handleClick);
    return () => document.removeEventListener("mousedown", handleClick);
  }, [open]);

  return (
    <div ref={ref} style={{ position: "relative", display: "inline-block" }}>
      {/* Trigger: the colored square */}
      <div
        onClick={(e) => { e.stopPropagation(); setOpen(!open); }}
        style={{
          width: 14, height: 14, borderRadius: 3,
          background: currentColor,
          cursor: "pointer",
          border: "2px solid rgba(255,255,255,0.8)",
          boxShadow: "0 0 0 1px rgba(0,0,0,0.15)",
          transition: "transform 0.1s",
          transform: open ? "scale(1.2)" : "scale(1)",
        }}
        title="Click to change color"
      />
      {/* Swatch popover */}
      {open && (
        <div style={{
          position: "absolute",
          top: "calc(100% + 6px)",
          left: 0,
          background: "#1e1e2e",
          borderRadius: 8,
          padding: 8,
          boxShadow: "0 4px 20px rgba(0,0,0,0.3)",
          zIndex: 150,
          display: "grid",
          gridTemplateColumns: "repeat(5, 1fr)",
          gap: 4,
          width: 140,
        }}>
          {COLOR_SWATCHES.map(color => (
            <div
              key={color}
              onClick={(e) => {
                e.stopPropagation();
                onSelect(color);
                setOpen(false);
              }}
              style={{
                width: 22, height: 22, borderRadius: 4,
                background: color,
                cursor: "pointer",
                border: color === currentColor
                  ? "2px solid #fff"
                  : "2px solid transparent",
                transition: "transform 0.1s",
              }}
              onMouseEnter={e => e.target.style.transform = "scale(1.15)"}
              onMouseLeave={e => e.target.style.transform = "scale(1)"}
            />
          ))}
        </div>
      )}
    </div>
  );
}


// =============================================================================
// TOOLTIP COMPONENT
// =============================================================================
// Custom tooltip that shows on hover over bars. Displays the full Likert label
// and the value (% or count) for each visible dataset.

const BarTooltip = ({ active, payload, usePercent, datasetList, colorList }) => {
  if (!active || !payload?.length) return null;

  // Find which Likert position we're hovering over
  const likertIdx = LIKERT_SHORT.indexOf(payload[0]?.payload?.label);
  const likertFull = likertIdx !== -1 ? DATA.likertScale[likertIdx] : "";

  return (
    <div style={{
      background: "#1e1e2e", border: "1px solid #333", borderRadius: 6,
      padding: "8px 12px", fontSize: 12, color: "#e0e0e0", lineHeight: 1.6,
    }}>
      <div style={{ fontWeight: 600, marginBottom: 4, color: "#a0a0b0" }}>{likertFull}</div>
      {payload.map((p, i) => {
        const dsIdx = datasetList.findIndex(ds => ds.name === p.name);
        return (
          <div key={i} style={{ display: "flex", alignItems: "center", gap: 6 }}>
            <span style={{
              width: 8, height: 8, borderRadius: 2,
              background: dsIdx !== -1 ? colorList[dsIdx] : (p.fill || p.color),
              display: "inline-block",
            }} />
            <span>{p.name}: </span>
            <span style={{ fontWeight: 600 }}>
              {usePercent ? `${p.value.toFixed(1)}%` : Math.round(p.value)}
            </span>
          </div>
        );
      })}
    </div>
  );
};


// =============================================================================
// QUESTION CHART COMPONENT
// =============================================================================
// Renders a single histogram card for one question. Shows grouped bars for each
// selected dataset, with an optional curve fit overlay.

function QuestionChart({
  question,           // question label string
  selectedDatasets,   // array of dataset indices to show
  usePercent,         // true = y-axis as %, false = raw counts
  likertMode,         // true = color bars by Likert value, false = by dataset
  fitMethod,          // "mom", "lsq", "kde", or "none"
  kdeBandwidth,       // minimum bandwidth for KDE (controlled by slider)
  datasetList,        // effective dataset array (cohort or aggregate)
  colorList,          // matching color array
  chartHeight = CHART_HEIGHT, // override height for modal view
}) {
  // Ref to measure the chart container width (needed to position curves)
  const containerRef = useRef(null);
  const [containerWidth, setContainerWidth] = useState(0);

  // Watch for container resize so curves stay aligned with bars
  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;
    const obs = new ResizeObserver(entries => {
      setContainerWidth(entries[0].contentRect.width);
    });
    obs.observe(el);
    return () => obs.disconnect();
  }, []);

  // Note: when calling a fit function, we need to pass kdeBandwidth to fitKDE.
  // This is inlined at each call site rather than wrapped in a helper function,
  // so that the useMemo dependency arrays stay clean for the linter.

  // Compute chart data and fit annotations, memoized so it only recalculates
  // when inputs change (prevents re-running on every parent re-render)
  const { chartData, yMax, annotations } = useMemo(() => {
    const statsMap = {};
    const annMap = {};

    selectedDatasets.forEach(dsIdx => {
      const ds = datasetList[dsIdx];
      if (!ds) return;
      statsMap[dsIdx] = computeStats(ds.questions[question]);

      // Compute annotation for the selected fit method
      if (fitMethod !== "none" && FIT_METHODS[fitMethod]?.fn) {
        const xSample = [0]; // dummy, we just want the annotation string
        const { annotation } = fitMethod === "kde"
          ? fitKDE(ds.questions[question], xSample, kdeBandwidth, usePercent)
          : FIT_METHODS[fitMethod].fn(ds.questions[question], xSample, usePercent);
        annMap[dsIdx] = annotation;
      }
    });

    // Build the 5-row data array for recharts (one row per Likert position)
    const rows = DATA.likertScale.map((likert, li) => {
      const row = { label: LIKERT_SHORT[li] };
      selectedDatasets.forEach(dsIdx => {
        const ds = datasetList[dsIdx];
        if (!ds) return;
        const counts = ds.questions[question];
        const t = statsMap[dsIdx]?.total || 0;
        const raw = counts[likert] || 0;
        row[ds.name] = usePercent && t > 0 ? (raw / t) * 100 : raw;
      });
      return row;
    });

    // Calculate y-axis max, accounting for both bars and curve peak
    let mx = 0;
    rows.forEach(r => {
      selectedDatasets.forEach(dsIdx => {
        const ds = datasetList[dsIdx];
        if (!ds) return;
        const v = r[ds.name];
        if (v > mx) mx = v;
      });
    });

    // If showing a curve, check if its peak exceeds the bar max
    if (fitMethod !== "none" && FIT_METHODS[fitMethod]?.fn) {
      const xPeakCheck = [];
      for (let t = -2.5; t <= 2.5; t += 0.1) xPeakCheck.push(t);
      selectedDatasets.forEach(dsIdx => {
        const ds = datasetList[dsIdx];
        if (!ds) return;
        const { y } = fitMethod === "kde"
          ? fitKDE(ds.questions[question], xPeakCheck, kdeBandwidth, usePercent)
          : FIT_METHODS[fitMethod].fn(ds.questions[question], xPeakCheck, usePercent);
        const peakVal = Math.max(...y);
        if (peakVal > mx) mx = peakVal;
      });
    }

    return { chartData: rows, yMax: Math.ceil(mx * 1.1) || 10, annotations: annMap };
  }, [question, selectedDatasets, usePercent, fitMethod, kdeBandwidth, datasetList]);

  // Compute SVG polyline points for each dataset's curve fit.
  // This runs whenever the container width, fit method, or data changes.
  const curvePolylines = useMemo(() => {
    if (fitMethod === "none" || !FIT_METHODS[fitMethod]?.fn || containerWidth === 0) return {};

    // Compute the plot area boundaries from known margins
    const plotLeft = CHART_MARGIN.left;
    const plotRight = containerWidth - CHART_MARGIN.right;
    const plotTop = CHART_MARGIN.top;
    const plotBottom = chartHeight - CHART_MARGIN.bottom;
    const plotWidth = plotRight - plotLeft;
    const plotHeight = plotBottom - plotTop;

    // 5 bar centers, evenly distributed across the plot area
    const catCenters = [0, 1, 2, 3, 4].map(
      i => plotLeft + (i + 0.5) * plotWidth / 5
    );

    // Map a continuous Likert value to pixel x by interpolating between centers
    const dataToPixelX = (val) => {
      const idx = val + 2; // shift: -2 -> 0, +2 -> 4
      if (idx < 0) return catCenters[0] + idx * (catCenters[1] - catCenters[0]);
      if (idx > 4) return catCenters[4] + (idx - 4) * (catCenters[4] - catCenters[3]);
      const lo = Math.max(0, Math.min(3, Math.floor(idx)));
      return catCenters[lo] + (idx - lo) * (catCenters[lo + 1] - catCenters[lo]);
    };

    // Map a y-value (%) to pixel y (inverted: higher values = lower pixels)
    const dataToPixelY = (val) => {
      const clamped = Math.min(val, yMax);
      return plotBottom - (clamped / yMax) * plotHeight;
    };

    // Sample x-values for smooth curves
    const xCurve = [];
    for (let t = -2.8; t <= 2.81; t += 0.04) xCurve.push(Math.round(t * 100) / 100);

    const result = {};
    selectedDatasets.forEach(dsIdx => {
      const ds = datasetList[dsIdx];
      if (!ds) return;
      const { y: yValues } = fitMethod === "kde"
        ? fitKDE(ds.questions[question], xCurve, kdeBandwidth, usePercent)
        : FIT_METHODS[fitMethod].fn(ds.questions[question], xCurve, usePercent);
      const pts = [];
      xCurve.forEach((x, i) => {
        const px = dataToPixelX(x);
        const py = dataToPixelY(yValues[i]);
        if (isFinite(px) && isFinite(py)) pts.push(`${px.toFixed(1)},${py.toFixed(1)}`);
      });
      if (pts.length > 1) result[dsIdx] = pts.join(" ");
    });
    return result;
  }, [containerWidth, fitMethod, kdeBandwidth, usePercent, selectedDatasets, datasetList, question, yMax, chartHeight]);

  const showCurve = fitMethod !== "none";

  return (
    <div style={{
      background: "#fafafa", borderRadius: 8,
      padding: "12px 8px 4px 8px", border: "1px solid #e5e5e5",
    }}>
      {/* Question title: hover over the first word to see the full Canvas question text */}
      <div style={{
        fontSize: 13, fontWeight: 600, color: "#1a1a2e",
        padding: "0 8px 4px 8px", lineHeight: 1.3,
        fontFamily: "'Source Serif 4', 'Georgia', serif",
      }}>
        {FULL_QUESTIONS[question] ? (() => {
          const firstSpace = question.indexOf(" ");
          const firstWord = firstSpace > 0 ? question.slice(0, firstSpace) : question;
          const rest = firstSpace > 0 ? question.slice(firstSpace) : "";
          return (
            <>
              <InfoTooltip text={
                <><strong>Full question text:</strong><br /><br />"{FULL_QUESTIONS[question]}"</>
              } width={300}>
                <span style={{
                  borderBottom: "1px dotted #999",
                  cursor: "help",
                }}>
                  {firstWord}
                </span>
              </InfoTooltip>
              {rest}
            </>
          );
        })() : question}
      </div>

      {/* Fit annotation (μ, σ, etc.) shown below title when curve is active */}
      {showCurve && (
        <div style={{ padding: "0 8px 4px", display: "flex", gap: 12, flexWrap: "wrap" }}>
          {selectedDatasets.map(dsIdx => (
            <span key={dsIdx} style={{ fontSize: 10, color: colorList[dsIdx], fontWeight: 600 }}>
              {annotations[dsIdx] || ""}
            </span>
          ))}
        </div>
      )}

      {/* Chart container: position relative so the SVG overlay can sit on top */}
      <div ref={containerRef} style={{ position: "relative", width: "100%", height: chartHeight }}>
        {/* The recharts bar chart */}
        <ResponsiveContainer width="100%" height={chartHeight}>
          <BarChart data={chartData} margin={{ top: 4, right: 8, left: -20, bottom: 0 }}>
            <XAxis
              dataKey="label"
              tick={{ fontSize: 11, fill: "#666" }}
              axisLine={{ stroke: "#ddd" }}
              tickLine={false}
            />
            <YAxis
              domain={[0, yMax]}
              tick={{ fontSize: 10, fill: "#999" }}
              axisLine={false} tickLine={false}
              tickFormatter={v => usePercent ? `${Math.round(v)}%` : Math.round(v)}
            />
            <Tooltip content={
              <BarTooltip usePercent={usePercent} datasetList={datasetList} colorList={colorList} />
            } />

            {selectedDatasets.map(dsIdx => {
              const ds = datasetList[dsIdx];
              if (!ds) return null;
              return likertMode ? (
                <Bar
                  key={ds.name} dataKey={ds.name}
                  fillOpacity={showCurve ? 0.5 : 0.8}
                  radius={[3, 3, 0, 0]} maxBarSize={40}
                  isAnimationActive={false}
                >
                  {chartData.map((_, idx) => (
                    <Cell key={idx} fill={LIKERT_COLORS[idx]} />
                  ))}
                </Bar>
              ) : (
                <Bar
                  key={ds.name} dataKey={ds.name}
                  fill={colorList[dsIdx]}
                  fillOpacity={showCurve ? 0.5 : 0.8}
                  radius={[3, 3, 0, 0]} maxBarSize={40}
                  isAnimationActive={false}
                />
              );
            })}
          </BarChart>
        </ResponsiveContainer>

        {/* SVG curve overlay: absolutely positioned on top of the chart.
            pointerEvents: "none" lets mouse events pass through to the bars below. */}
        {showCurve && containerWidth > 0 && (
          <svg style={{
            position: "absolute", top: 0, left: 0,
            width: "100%", height: "100%",
            pointerEvents: "none",
          }}>
            {selectedDatasets.map(dsIdx => (
              curvePolylines[dsIdx] ? (
                <polyline
                  key={dsIdx}
                  points={curvePolylines[dsIdx]}
                  fill="none"
                  stroke={colorList[dsIdx]}
                  strokeWidth={2.5}
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  opacity={0.9}
                />
              ) : null
            ))}
          </svg>
        )}
      </div>
    </div>
  );
}


// =============================================================================
// MEAN COMPARISON CHART COMPONENT
// =============================================================================
// Horizontal bar chart showing the mean Likert score (-2 to +2) for each
// question, grouped by dataset. This is the "report-ready" view.

// Likert-to-numeric map used by MeanChart (defined at module scope to satisfy lint)
const LIKERT_TO_NUM = {
  "Very untrue of me": -2, "Somewhat untrue of me": -1,
  "Neutral": 0, "Somewhat true of me": 1, "Very true of me": 2,
};

function MeanChart({ selectedDatasets, datasetList, colorList, fullLabels }) {
  // Compute mean for each question × dataset combination
  const meanData = useMemo(() => {
    return DATA.questions.map(q => {
      const row = {
        question: fullLabels ? (FULL_QUESTIONS[q] || q) : q,
      };
      selectedDatasets.forEach(dsIdx => {
        const ds = datasetList[dsIdx];
        if (!ds) return;
        const counts = ds.questions[q];
        const total = Object.values(counts).reduce((a, b) => a + b, 0);
        if (total === 0) { row[ds.name] = 0; return; }
        let sum = 0;
        for (const [label, count] of Object.entries(counts)) {
          sum += LIKERT_TO_NUM[label] * count;
        }
        row[ds.name] = sum / total;
      });
      return row;
    });
  }, [selectedDatasets, datasetList, fullLabels]);

  return (
    <div style={{
      background: "#fafafa", borderRadius: 8,
      padding: "16px 8px 4px 8px", border: "1px solid #e5e5e5",
    }}>
      <div style={{
        fontSize: 15, fontWeight: 700, color: "#1a1a2e",
        padding: "0 8px 12px 8px",
        fontFamily: "'Source Serif 4', 'Georgia', serif",
      }}>
        Mean Score Comparison (-2 to +2)
      </div>
      <ResponsiveContainer width="100%" height={fullLabels ? 900 : 520}>
        <BarChart data={meanData} layout="vertical" margin={{ top: 0, right: 20, left: 10, bottom: 0 }}>
          <XAxis
            type="number" domain={[-2, 2]}
            tick={{ fontSize: 11, fill: "#666" }}
            axisLine={{ stroke: "#ddd" }} tickLine={false}
          />
          <YAxis
            type="category" dataKey="question" width={fullLabels ? 380 : 160}
            tick={{ fontSize: fullLabels ? 10 : 11, fill: "#444" }}
            axisLine={false} tickLine={false}
          />
          <Tooltip content={({ active, payload, label }) => {
            if (!active || !payload?.length) return null;
            return (
              <div style={{
                background: "#1e1e2e", border: "1px solid #333", borderRadius: 6,
                padding: "8px 12px", fontSize: 12, color: "#e0e0e0",
              }}>
                <div style={{ fontWeight: 600, marginBottom: 4, color: "#a0a0b0" }}>
                  {label}
                </div>
                {payload.map((p, i) => (
                  <div key={i} style={{ display: "flex", alignItems: "center", gap: 6 }}>
                    <span style={{
                      width: 8, height: 8, borderRadius: 2,
                      background: p.fill || p.color, display: "inline-block",
                    }} />
                    <span>{p.name}: </span>
                    <span style={{ fontWeight: 600 }}>{p.value.toFixed(2)}</span>
                  </div>
                ))}
              </div>
            );
          }} />
          <Legend wrapperStyle={{ fontSize: 12 }} />
          {selectedDatasets.map(dsIdx => {
            const ds = datasetList[dsIdx];
            if (!ds) return null;
            return (
              <Bar
                key={ds.name} dataKey={ds.name}
                fill={colorList[dsIdx]} fillOpacity={0.8}
                radius={[0, 3, 3, 0]} maxBarSize={14}
              />
            );
          })}
        </BarChart>
      </ResponsiveContainer>
    </div>
  );
}


// =============================================================================
// SHARED HELPER: compute mean for a question's Likert counts
// =============================================================================

function questionMean(counts) {
  const total = Object.values(counts).reduce((a, b) => a + b, 0);
  if (total === 0) return 0;
  let sum = 0;
  for (const [label, count] of Object.entries(counts)) {
    sum += LIKERT_TO_NUM[label] * count;
  }
  return sum / total;
}


// =============================================================================
// DELTA VIEW COMPONENT
// =============================================================================
// Shows the shift in mean score between exactly two selected datasets.
// Each question gets a row with the two means, the delta, and a color-coded bar.
// This is the "leadership slide" view: "+0.87 improvement on every question."

function DeltaView({ selectedDatasets, datasetList, colorList, fullLabels }) {
  const [groupByTheme, setGroupByTheme] = useState(false);

  // Need exactly 2 datasets selected for a meaningful comparison
  if (selectedDatasets.length !== 2) {
    return (
      <div style={{
        background: "#fafafa", borderRadius: 8, padding: 40,
        border: "1px solid #e5e5e5", textAlign: "center", color: "#999",
      }}>
        {selectedDatasets.length < 2
          ? "Select exactly 2 datasets to see the delta comparison."
          : `${selectedDatasets.length} datasets selected. Please select exactly 2 for a delta comparison (a baseline and a comparison).`
        }
      </div>
    );
  }

  // Use first two selected datasets as "baseline" and "comparison"
  const baseIdx = selectedDatasets[0];
  const compIdx = selectedDatasets[1];
  const baseds = datasetList[baseIdx];
  const compDs = datasetList[compIdx];
  if (!baseds || !compDs) return null;

  // Helper: compute standard deviation from Likert counts
  const questionStd = (counts) => {
    const total = Object.values(counts).reduce((a, b) => a + b, 0);
    if (total === 0) return 1;
    const mean = questionMean(counts);
    let sumSq = 0;
    for (const [label, count] of Object.entries(counts)) {
      sumSq += (LIKERT_TO_NUM[label] - mean) ** 2 * count;
    }
    return Math.sqrt(sumSq / total);
  };

  // Cohen's d: (mean2 - mean1) / pooled_std
  // pooled_std = sqrt((std1² + std2²) / 2)
  // Effect size: |d| < 0.2 negligible, 0.2-0.5 small, 0.5-0.8 medium, ≥ 0.8 large
  const cohensD = (counts1, counts2) => {
    const std1 = questionStd(counts1);
    const std2 = questionStd(counts2);
    const pooled = Math.sqrt((std1 * std1 + std2 * std2) / 2);
    if (pooled < 0.01) return 0;
    return (questionMean(counts2) - questionMean(counts1)) / pooled;
  };

  const effectLabel = (d) => {
    const abs = Math.abs(d);
    if (abs < 0.2) return { text: "Negligible", color: "#999" };
    if (abs < 0.5) return { text: "Small", color: "#ca8a04" };
    if (abs < 0.8) return { text: "Medium", color: "#2563eb" };
    return { text: "Large", color: "#16a34a" };
  };

  // Compute deltas and Cohen's d for all 20 questions
  const rows = DATA.questions.map(q => {
    const baseMean = questionMean(baseds.questions[q]);
    const compMean = questionMean(compDs.questions[q]);
    const delta = compMean - baseMean;
    const d = cohensD(baseds.questions[q], compDs.questions[q]);
    return { question: q, baseMean, compMean, delta, d };
  });

  // Also compute category-level deltas and Cohen's d
  const catRows = Object.entries(QUESTION_CATEGORIES).map(([cat, qs]) => {
    const baseMeans = qs.map(q => questionMean(baseds.questions[q]));
    const compMeans = qs.map(q => questionMean(compDs.questions[q]));
    const baseAvg = baseMeans.reduce((a, b) => a + b, 0) / baseMeans.length;
    const compAvg = compMeans.reduce((a, b) => a + b, 0) / compMeans.length;
    // Category-level Cohen's d: average the per-question d values
    const dValues = qs.map(q => cohensD(baseds.questions[q], compDs.questions[q]));
    const avgD = dValues.reduce((a, b) => a + b, 0) / dValues.length;
    return { category: cat, baseAvg, compAvg, delta: compAvg - baseAvg, d: avgD };
  });

  const maxAbsDelta = Math.max(...rows.map(r => Math.abs(r.delta)), 0.01);

  return (
    <div style={{ background: "#fafafa", borderRadius: 8, padding: "16px 20px", border: "1px solid #e5e5e5" }}>
      <div style={{
        fontSize: 15, fontWeight: 700, color: "#1a1a2e",
        fontFamily: "'Source Serif 4', 'Georgia', serif",
        marginBottom: 4,
      }}>
        Mean Score Shift
      </div>
      <div style={{ fontSize: 12, color: "#888", marginBottom: 16, display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: 8 }}>
        <div>
          <span style={{ color: colorList[baseIdx], fontWeight: 600 }}>{baseds.name}</span>
          {" \u2192 "}
          <span style={{ color: colorList[compIdx], fontWeight: 600 }}>{compDs.name}</span>
        </div>
        <div style={{ display: "flex", gap: 0 }}>
          <button onClick={() => setGroupByTheme(false)} style={{
            padding: "4px 10px", fontSize: 11, fontWeight: 600, cursor: "pointer",
            border: "1px solid #ddd", borderRight: "none", borderRadius: "5px 0 0 5px",
            background: !groupByTheme ? "#1a1a2e" : "#fff",
            color: !groupByTheme ? "#fff" : "#666",
            fontFamily: "inherit",
          }}>Survey Order</button>
          <button onClick={() => setGroupByTheme(true)} style={{
            padding: "4px 10px", fontSize: 11, fontWeight: 600, cursor: "pointer",
            border: "1px solid #ddd", borderRadius: "0 5px 5px 0",
            background: groupByTheme ? "#1a1a2e" : "#fff",
            color: groupByTheme ? "#fff" : "#666",
            fontFamily: "inherit",
          }}>Grouped by Theme</button>
        </div>
      </div>

      {/* Category summary cards */}
      <div style={{ display: "flex", gap: 12, marginBottom: 20, flexWrap: "wrap" }}>
        {catRows.map(cr => (
          <div key={cr.category} style={{
            flex: "1 1 200px", background: "#fff", borderRadius: 8,
            padding: "12px 16px", border: "1px solid #e5e5e5",
          }}>
            <div style={{
              fontSize: 11, fontWeight: 600, textTransform: "uppercase",
              color: CATEGORY_COLORS[cr.category], letterSpacing: "0.03em", marginBottom: 6,
            }}>
              {cr.category}
            </div>
            <div style={{ display: "flex", alignItems: "baseline", gap: 8 }}>
              <span style={{
                fontSize: 28, fontWeight: 700,
                color: cr.delta >= 0 ? "#16a34a" : "#dc2626",
                fontFamily: "'DM Sans', sans-serif",
              }}>
                {cr.delta >= 0 ? "+" : ""}{cr.delta.toFixed(2)}
              </span>
              <span style={{ fontSize: 11, color: "#999" }}>
                {cr.baseAvg.toFixed(2)} {"\u2192"} {cr.compAvg.toFixed(2)}
              </span>
            </div>
            <div style={{ fontSize: 10, color: effectLabel(cr.d).color, fontWeight: 600, marginTop: 4 }}>
              d = {cr.d.toFixed(2)} ({effectLabel(cr.d).text})
            </div>
          </div>
        ))}
      </div>

      {/* Per-question table */}
      <div style={{ overflowX: "auto" }}>
        <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 12 }}>
          <thead>
            <tr style={{ borderBottom: "2px solid #e0e0e0" }}>
              <th style={{ textAlign: "left", padding: "8px 10px", color: "#666", fontWeight: 600 }}>Question</th>
              <th style={{ textAlign: "center", padding: "8px 10px", color: colorList[baseIdx], fontWeight: 600, width: 80 }}>
                {baseds.name.split(" - ")[0]}
              </th>
              <th style={{ textAlign: "center", padding: "8px 10px", color: colorList[compIdx], fontWeight: 600, width: 80 }}>
                {compDs.name.split(" - ")[0]}
              </th>
              <th style={{ textAlign: "center", padding: "8px 10px", color: "#444", fontWeight: 600, width: 80 }}>
                <InfoTooltip position="below" width={240} text={<>
                  <strong>Delta (Mean Shift)</strong><br /><br />
                  The difference in average score between the two datasets.
                  Positive values (green) mean the comparison group scored higher;
                  negative (red) means lower.
                </>}>
                  <span style={{ borderBottom: "1px dotted #999", cursor: "help" }}>Delta</span>
                </InfoTooltip>
              </th>
              <th style={{ textAlign: "center", padding: "8px 10px", color: "#444", fontWeight: 600, width: 100 }}>
                <InfoTooltip position="below" width={300} text={<>
                  <strong>Cohen's <em>d</em> (Effect Size)</strong><br /><br />
                  Measures how meaningful the shift is relative to the spread
                  of responses. A question with a big delta but high variance
                  will have a smaller <em>d</em> than one with a modest delta but
                  tight agreement.<br /><br />
                  <span style={{ color: "#16a34a" }}><strong>&ge; 0.8 Large</strong></span><br />
                  <span style={{ color: "#16a34a", fontSize: 10, marginLeft: 0 }}>InSight clearly moved the needle on this skill</span><br /><br />
                  <span style={{ color: "#2563eb" }}><strong>0.5-0.8 Medium</strong></span><br />
                  <span style={{ color: "#2563eb", fontSize: 10 }}>Meaningful improvement, solid evidence of impact</span><br /><br />
                  <span style={{ color: "#ca8a04" }}><strong>0.2-0.5 Small</strong></span><br />
                  <span style={{ color: "#ca8a04", fontSize: 10 }}>Some improvement, but varied across students</span><br /><br />
                  <span style={{ color: "#999" }}><strong>&lt; 0.2 Negligible</strong></span><br />
                  <span style={{ color: "#999", fontSize: 10 }}>Not enough movement to attribute to the program</span>
                </>}>
                  <span style={{ borderBottom: "1px dotted #999", cursor: "help" }}>Cohen's <em>d</em></span>
                </InfoTooltip>
              </th>
              <th style={{ textAlign: "center", padding: "8px 10px", color: "#444", fontWeight: 600, width: 150 }}>
                <InfoTooltip position="below" width={220} text={<>
                  <strong>Delta Bar</strong><br /><br />
                  Visual representation of the raw mean shift. Green bars
                  grow right for positive deltas, red bars grow left for
                  negative. Width is scaled relative to the largest shift
                  in the table.
                </>}>
                  <span style={{ borderBottom: "1px dotted #999", cursor: "help" }}>Shift</span>
                </InfoTooltip>
              </th>
            </tr>
          </thead>
          <tbody>
            {(() => {
              // Build the display rows: either in survey order or grouped by theme
              const displayRows = groupByTheme
                ? Object.entries(QUESTION_CATEGORIES).flatMap(([cat, qs]) => {
                    // Category header row + its question rows
                    const catQuestionRows = qs
                      .map(q => rows.find(r => r.question === q))
                      .filter(Boolean);
                    return [{ type: "header", category: cat }, ...catQuestionRows.map(r => ({ type: "row", ...r }))];
                  })
                : rows.map(r => ({ type: "row", ...r }));

              return displayRows.map((item, i) => {
                if (item.type === "header") {
                  // Category divider row
                  return (
                    <tr key={`cat-${item.category}`} style={{
                      background: "#f0f0ec",
                      borderTop: i > 0 ? "2px solid #ddd" : "none",
                    }}>
                      <td colSpan={6} style={{
                        padding: "6px 10px", fontWeight: 700, fontSize: 11,
                        textTransform: "uppercase", letterSpacing: "0.03em",
                        color: CATEGORY_COLORS[item.category],
                      }}>
                        {item.category}
                      </td>
                    </tr>
                  );
                }

                const r = item;
                const cat = Object.entries(QUESTION_CATEGORIES).find(([, qs]) => qs.includes(r.question));
                const catColor = cat ? CATEGORY_COLORS[cat[0]] : "#ddd";
                const barWidth = (Math.abs(r.delta) / maxAbsDelta) * 100;

                return (
                  <tr key={r.question} style={{
                    borderBottom: "1px solid #f0f0f0",
                    borderLeft: `3px solid ${catColor}`,
                  }}>
                    <td style={{ padding: "7px 10px", color: "#333", lineHeight: 1.4 }}>
                      {fullLabels ? (FULL_QUESTIONS[r.question] || r.question) : r.question}
                    </td>
                    <td style={{ textAlign: "center", padding: "7px 10px", color: "#666", fontFamily: "monospace" }}>
                      {r.baseMean.toFixed(2)}
                    </td>
                    <td style={{ textAlign: "center", padding: "7px 10px", color: "#666", fontFamily: "monospace" }}>
                      {r.compMean.toFixed(2)}
                    </td>
                    <td style={{
                      textAlign: "center", padding: "7px 10px", fontWeight: 700,
                      fontFamily: "monospace",
                      color: r.delta >= 0 ? "#16a34a" : "#dc2626",
                    }}>
                      {r.delta >= 0 ? "+" : ""}{r.delta.toFixed(2)}
                    </td>
                    <td style={{
                      textAlign: "center", padding: "7px 10px",
                      fontFamily: "monospace", fontSize: 11,
                      color: effectLabel(r.d).color, fontWeight: 600,
                    }}>
                      {r.d.toFixed(2)}
                      <span style={{ fontSize: 9, fontFamily: "sans-serif", fontWeight: 400, marginLeft: 4, opacity: 0.8 }}>
                        {effectLabel(r.d).text}
                      </span>
                    </td>
                    <td style={{ padding: "7px 10px" }}>
                      <div style={{
                        position: "relative", height: 14, background: "#f0f0f0",
                        borderRadius: 7, overflow: "hidden",
                      }}>
                        <div style={{
                          position: "absolute",
                          top: 0, height: "100%",
                          borderRadius: 7,
                          background: r.delta >= 0 ? "#16a34a" : "#dc2626",
                          opacity: 0.7,
                          ...(r.delta >= 0
                            ? { left: "50%", width: `${barWidth / 2}%` }
                            : { right: "50%", width: `${barWidth / 2}%` }
                          ),
                        }} />
                        <div style={{
                          position: "absolute", left: "50%", top: 0,
                          width: 1, height: "100%", background: "#ccc",
                        }} />
                      </div>
                    </td>
                  </tr>
                );
              });
            })()}
          </tbody>
        </table>
      </div>
    </div>
  );
}


// =============================================================================
// CATEGORY VIEW COMPONENT
// =============================================================================
// Groups the 20 questions into Wellbeing, Financial Literacy, and
// Career Positioning, and shows aggregate mean scores per category per dataset.
// Includes both the category-level summary and the per-question breakdown.

function CategoryView({ selectedDatasets, datasetList, colorList, fullLabels }) {
  // Compute means at category and question level
  const categoryData = useMemo(() => {
    return Object.entries(QUESTION_CATEGORIES).map(([category, qs]) => {
      const datasetMeans = {};
      selectedDatasets.forEach(dsIdx => {
        const ds = datasetList[dsIdx];
        if (!ds) return;
        const qMeans = qs.map(q => questionMean(ds.questions[q]));
        datasetMeans[ds.name] = qMeans.reduce((a, b) => a + b, 0) / qMeans.length;
      });

      // Per-question data for the breakdown table
      const questionRows = qs.map(q => {
        const row = { question: q };
        selectedDatasets.forEach(dsIdx => {
          const ds = datasetList[dsIdx];
          if (!ds) return;
          row[ds.name] = questionMean(ds.questions[q]);
        });
        return row;
      });

      return { category, datasetMeans, questionRows, questions: qs };
    });
  }, [selectedDatasets, datasetList]);

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>
      {categoryData.map(({ category, datasetMeans, questionRows }) => (
        <div key={category} style={{
          background: "#fafafa", borderRadius: 8,
          border: "1px solid #e5e5e5", overflow: "hidden",
        }}>
          {/* Category header with colored accent */}
          <div style={{
            padding: "14px 20px",
            borderBottom: "1px solid #e5e5e5",
            borderLeft: `4px solid ${CATEGORY_COLORS[category]}`,
            display: "flex", alignItems: "center", justifyContent: "space-between",
            flexWrap: "wrap", gap: 12,
          }}>
            <div>
              <div style={{
                fontSize: 16, fontWeight: 700, color: "#1a1a2e",
                fontFamily: "'Source Serif 4', 'Georgia', serif",
              }}>
                {category}
              </div>
              <div style={{ fontSize: 11, color: "#999", marginTop: 2 }}>
                {questionRows.length} questions
              </div>
            </div>
            {/* Category-level means as chips */}
            <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
              {selectedDatasets.map(dsIdx => {
                const ds = datasetList[dsIdx];
                if (!ds) return null;
                const mean = datasetMeans[ds.name];
                return (
                  <div key={dsIdx} style={{
                    padding: "4px 12px", borderRadius: 20,
                    background: colorList[dsIdx] + "18",
                    border: `1px solid ${colorList[dsIdx]}44`,
                    fontSize: 12, fontWeight: 600,
                    color: colorList[dsIdx],
                  }}>
                    {ds.name}: <span style={{ fontFamily: "monospace" }}>{mean?.toFixed(2) ?? "—"}</span>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Per-question breakdown */}
          <div style={{ padding: "0 20px 12px" }}>
            <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 12 }}>
              <thead>
                <tr style={{ borderBottom: "1px solid #e8e8e8" }}>
                  <th style={{ textAlign: "left", padding: "8px 6px", color: "#999", fontWeight: 600, fontSize: 11 }}>
                    Question
                  </th>
                  {selectedDatasets.map(dsIdx => {
                    const ds = datasetList[dsIdx];
                    if (!ds) return null;
                    return (
                      <th key={dsIdx} style={{
                        textAlign: "center", padding: "8px 6px",
                        color: colorList[dsIdx], fontWeight: 600, fontSize: 11, width: 90,
                      }}>
                        {ds.name.split(" - ").pop()}
                      </th>
                    );
                  })}
                </tr>
              </thead>
              <tbody>
                {questionRows.map(row => (
                  <tr key={row.question} style={{ borderBottom: "1px solid #f4f4f4" }}>
                    <td style={{ padding: "6px 6px", color: "#444", lineHeight: 1.4 }}>
                      {fullLabels ? (FULL_QUESTIONS[row.question] || row.question) : row.question}
                    </td>
                    {selectedDatasets.map(dsIdx => {
                      const ds = datasetList[dsIdx];
                      if (!ds) return null;
                      const val = row[ds.name];
                      // Color intensity based on value: green for positive, red for negative
                      const intensity = val != null ? Math.min(Math.abs(val) / 2, 1) : 0;
                      const bg = val >= 0
                        ? `rgba(22, 163, 74, ${intensity * 0.15})`
                        : `rgba(220, 38, 38, ${intensity * 0.15})`;
                      return (
                        <td key={dsIdx} style={{
                          textAlign: "center", padding: "6px 6px",
                          fontFamily: "monospace", fontWeight: 600, fontSize: 12,
                          color: "#555", background: bg,
                        }}>
                          {val?.toFixed(2) ?? "—"}
                        </td>
                      );
                    })}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      ))}
    </div>
  );
}


// =============================================================================
// MAIN APP COMPONENT
// =============================================================================
// Top-level component that manages all state and renders the control panel,
// legends, and chart views (histogram grid or mean comparison).

export default function App() {
  // --- State ---
  // Which dataset indices are currently selected (toggled on/off by user)
  const [selected, setSelected] = useState([0, 3]); // default: Kickoff 2027 + Exit 2026

  // Display options
  const [usePercent, setUsePercent] = useState(true);    // Y-axis: % vs raw count
  const [likertMode, setLikertMode] = useState(false);   // Bar color: by dataset vs by Likert
  const [fitMethod, setFitMethod] = useState("mom");     // Curve fit method
  const [kdeBandwidth, setKdeBandwidth] = useState(0.7);  // KDE minimum bandwidth (slider)
  const [view, setView] = useState("grid");              // "grid" (histograms) or "means"
  const [aggregate, setAggregate] = useState(false);     // Cohort vs Aggregate toggle
  const [modalQuestion, setModalQuestion] = useState(null); // Which question is expanded (null = closed)
  const [colorOverrides, setColorOverrides] = useState({}); // {datasetName: "#hex"} custom color picks
  const [fullLabels, setFullLabels] = useState(false);      // Show full question text in means/delta/categories

  // Close modal on Escape key
  useEffect(() => {
    const handleKey = (e) => { if (e.key === "Escape") setModalQuestion(null); };
    window.addEventListener("keydown", handleKey);
    return () => window.removeEventListener("keydown", handleKey);
  }, []);

  // --- Derived values ---
  const effectiveDatasets = aggregate ? AGGREGATE_DATASETS : DATA.datasets;

  // Build the color array for the current dataset list.
  // Priority: user override (by name) > defaults > overflow (generated).
  const effectiveColors = useMemo(() => {
    return effectiveDatasets.map((ds, idx) => {
      // 1. Check user override
      if (colorOverrides[ds.name]) return colorOverrides[ds.name];
      // 2. Check aggregate defaults (by name)
      if (AGG_DEFAULTS[ds.name]) return AGG_DEFAULTS[ds.name];
      // 3. Use default palette by index
      if (idx < DEFAULT_PALETTE.length) return DEFAULT_PALETTE[idx];
      // 4. Overflow: generate a color
      return generateOverflowColor(DEFAULT_PALETTE, idx);
    });
  }, [effectiveDatasets, colorOverrides]);

  // Handler: set a custom color for a dataset (stored by name)
  const setDatasetColor = (dsName, color) => {
    setColorOverrides(prev => ({ ...prev, [dsName]: color }));
  };

  // Compute median Silverman's and Scott's rule bandwidths across all visible
  // dataset/question combinations. These become anchor points on the KDE slider
  // so you can see where the standard rules would land relative to your setting.
  const bandwidthAnchors = useMemo(() => {
    const silvermanVals = [];
    const scottVals = [];
    selected.forEach(dsIdx => {
      const ds = effectiveDatasets[dsIdx];
      if (!ds) return;
      DATA.questions.forEach(q => {
        const rules = computeBandwidthRules(ds.questions[q]);
        if (rules) {
          silvermanVals.push(rules.silverman);
          scottVals.push(rules.scott);
        }
      });
    });
    // Median helper
    const median = arr => {
      if (arr.length === 0) return null;
      const s = [...arr].sort((a, b) => a - b);
      const mid = Math.floor(s.length / 2);
      return s.length % 2 ? s[mid] : (s[mid - 1] + s[mid]) / 2;
    };
    return {
      silverman: median(silvermanVals),
      scott: median(scottVals),
    };
  }, [selected, effectiveDatasets]);

  // --- Handlers ---
  // Toggle a single dataset on or off
  const toggle = idx => setSelected(prev =>
    prev.includes(idx) ? prev.filter(i => i !== idx) : [...prev, idx]
  );

  // Switch between cohort and aggregate view, auto-selecting all datasets
  const handleAggToggle = (val) => {
    setAggregate(val);
    if (val) {
      setSelected(AGGREGATE_DATASETS.map((_, i) => i)); // select all aggregates
    } else {
      setSelected([0, 3]); // reset to default cohort selection
    }
  };

  // --- Reusable UI components ---

  // Toggle button (used in all the control groups)
  const Btn = ({ active, onClick, children, pos, tooltip }) => {
    const btn = (
      <button onClick={onClick} style={{
        padding: "6px 14px", border: "1px solid #ddd",
        borderRight: pos === "left" || pos === "mid" ? "none" : "1px solid #ddd",
        borderRadius: pos === "left" ? "6px 0 0 6px" : pos === "right" ? "0 6px 6px 0" : "0",
        background: active ? "#1a1a2e" : "#fff",
        color: active ? "#fff" : "#666",
        fontWeight: 600, fontSize: 12, cursor: "pointer",
        fontFamily: "inherit", transition: "all 0.12s",
      }}>{children}</button>
    );
    if (tooltip) return <InfoTooltip text={tooltip} position="below">{btn}</InfoTooltip>;
    return btn;
  };

  // Control group label
  const Label = ({ children }) => (
    <div style={{
      fontSize: 11, fontWeight: 600, color: "#888",
      textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: 6,
    }}>{children}</div>
  );

  // --- Render ---
  return (
    <div style={{
      minHeight: "100vh",
      background: "#f5f5f0",
      fontFamily: "'DM Sans', 'Segoe UI', system-ui, sans-serif",
    }}>
      {/* Google Fonts import for the serif headings */}
      <link
        href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Source+Serif+4:wght@600;700&display=swap"
        rel="stylesheet"
      />

      {/* ---- HEADER ---- */}
      <div style={{ background: "#1a1a2e", padding: "20px 24px", color: "#fff" }}>
        <div style={{
          fontSize: 22, fontWeight: 700,
          fontFamily: "'Source Serif 4', 'Georgia', serif",
          letterSpacing: "-0.02em",
        }}>
          InSight Survey Comparison
        </div>
        <div style={{ fontSize: 13, color: "#a0a0b0", marginTop: 4 }}>
          Likert response distributions with curve fit overlay
        </div>
      </div>

      {/* ---- CONTROLS BAR ---- */}
      <div style={{
        padding: "16px 24px", background: "#fff",
        borderBottom: "1px solid #e0e0e0",
        display: "flex", flexDirection: "column", gap: 12,
      }}>
        {/* Dataset selection (left side) */}
        <div style={{ flex: "1 1 auto" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 6 }}>
            <Label>Datasets</Label>
            {/* Cohort vs Aggregate toggle */}
            <div style={{ display: "flex", marginBottom: 6 }}>
              <Btn active={!aggregate} onClick={() => handleAggToggle(false)} pos="left">
                By Cohort
              </Btn>
              <Btn active={aggregate} onClick={() => handleAggToggle(true)} pos="right">
                Aggregate
              </Btn>
            </div>
          </div>
          {/* Individual dataset toggle buttons */}
          <div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
            {effectiveDatasets.map((ds, idx) => {
              const isOn = selected.includes(idx);
              const color = effectiveColors[idx];
              return (
                <div key={idx} style={{ display: "flex", alignItems: "center", gap: 4 }}>
                  {/* Color picker: click the swatch to change this dataset's color */}
                  <ColorPicker
                    currentColor={color}
                    onSelect={(c) => setDatasetColor(ds.name, c)}
                  />
                  {/* Dataset toggle button */}
                  <button onClick={() => toggle(idx)} style={{
                    padding: "6px 12px", borderRadius: 6,
                    border: `2px solid ${isOn ? color : "#ddd"}`,
                    background: isOn ? hexToLight(color) : "#fff",
                    color: isOn ? color : "#888",
                    fontWeight: 600, fontSize: 13, cursor: "pointer",
                    transition: "all 0.15s", fontFamily: "inherit",
                  }}>
                    {ds.name}
                    <span style={{ marginLeft: 6, fontWeight: 400, fontSize: 11, color: "#999" }}>
                      n={ds.n}
                    </span>
                  </button>
                </div>
              );
            })}
          </div>
        </div>

        {/* Right-side controls */}
        <div style={{ display: "flex", gap: 12, alignItems: "flex-start", flexWrap: "wrap" }}>
          {/* View toggle: Histograms vs Mean Scores */}
          <div>
            <Label>View</Label>
            <div style={{ display: "flex" }}>
              <Btn active={view === "grid"} onClick={() => setView("grid")} pos="left">
                Histograms
              </Btn>
              <Btn active={view === "means"} onClick={() => setView("means")} pos="mid">
                Means
              </Btn>
              <Btn active={view === "delta"} onClick={() => setView("delta")} pos="mid">
                Delta
              </Btn>
              <Btn active={view === "categories"} onClick={() => setView("categories")} pos="right">
                Categories
              </Btn>
            </div>
          </div>

          {/* Histogram-only controls (hidden when viewing means) */}
          {view === "grid" && (
            <>
              {/* Curve Fit method toggle + KDE slider stacked vertically */}
              <div>
                <Label>Curve Fit</Label>
                <div style={{ display: "flex" }}>
                  <Btn
                    active={fitMethod === "mom"} pos="left"
                    onClick={() => setFitMethod("mom")}
                    tooltip={<>
                      <strong>Method of Moments</strong><br /><br />
                      Computes the sample mean (μ) and standard deviation (σ) directly
                      from the Likert counts, then draws a normal distribution with
                      those parameters.<br /><br />
                      <span style={{ color: "#8f8" }}>✓ Instant, clean μ/σ for reporting</span><br />
                      <span style={{ color: "#f88" }}>✗ Assumes symmetry; can't capture skew</span>
                    </>}
                  >MoM</Btn>
                  <Btn
                    active={fitMethod === "lsq"} pos="mid"
                    onClick={() => setFitMethod("lsq")}
                    tooltip={<>
                      <strong>Least Squares Gaussian</strong><br /><br />
                      Finds the Gaussian curve that best fits the 5 observed bar
                      heights by minimizing the squared error between the curve
                      and the bars.<br /><br />
                      <span style={{ color: "#8f8" }}>✓ Hugs the bars more closely than MoM</span><br />
                      <span style={{ color: "#f88" }}>✗ Still forces a symmetric bell shape</span>
                    </>}
                  >LSQ</Btn>
                  <Btn
                    active={fitMethod === "kde"} pos="mid"
                    onClick={() => setFitMethod("kde")}
                    tooltip={<>
                      <strong>Kernel Density Estimation</strong><br /><br />
                      Nonparametric: places a small Gaussian "kernel" at every data point
                      and sums them to get a smooth density. No symmetry assumption, so it
                      can capture skew and heavy tails.<br /><br />
                      <span style={{ color: "#8f8" }}>✓ Faithful to actual data shape</span><br />
                      <span style={{ color: "#f88" }}>✗ Sensitive to bandwidth choice on discrete data</span>
                    </>}
                  >KDE</Btn>
                  <Btn
                    active={fitMethod === "none"} pos="right"
                    onClick={() => setFitMethod("none")}
                  >None</Btn>
                </div>

                {/* KDE bandwidth slider: appears directly below the curve fit buttons
                    when KDE is selected, keeping them as one visual unit */}
                {fitMethod === "kde" && (
                  <div style={{ marginTop: 8 }}>
                    <div style={{ fontSize: 10, fontWeight: 600, color: "#666", marginBottom: 4 }}>
                      Bandwidth: {kdeBandwidth.toFixed(2)}
                    </div>
                    <div style={{ position: "relative", width: 170 }}>
                      <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
                        <span style={{ fontSize: 9, color: "#999" }}>0.1</span>
                        <input
                          type="range"
                          min="0.1"
                          max="1.5"
                          step="0.05"
                          value={kdeBandwidth}
                          onChange={e => setKdeBandwidth(parseFloat(e.target.value))}
                          style={{ width: 110, cursor: "pointer" }}
                        />
                        <span style={{ fontSize: 9, color: "#999" }}>1.5</span>
                      </div>
                      {/* Anchor tick marks for Silverman's and Scott's rule */}
                      <div style={{ position: "relative", marginLeft: 18, width: 110, height: 26 }}>
                        {[
                          {
                            val: bandwidthAnchors.silverman,
                            label: "Silv.",
                            color: "#e85d04",
                            tickH: 6,
                            tip: <>
                              <strong>Silverman's Rule</strong><br /><br />
                              Robust bandwidth estimate that uses both standard deviation
                              and interquartile range. Often a good starting point for
                              roughly normal data.<br /><br />
                              Value shown is the median across all visible charts.
                              Click to snap the slider.
                            </>
                          },
                          {
                            val: bandwidthAnchors.scott,
                            label: "Scott",
                            color: "#2563eb",
                            tickH: 16,
                            tip: <>
                              <strong>Scott's Rule</strong><br /><br />
                              Bandwidth estimate based on standard deviation and sample
                              size. Best suited for large, roughly normal datasets.<br /><br />
                              Value shown is the median across all visible charts.
                              Click to snap the slider.
                            </>
                          },
                        ].map(anchor => {
                          if (anchor.val == null) return null;
                          const clamped = Math.max(0.1, Math.min(1.5, anchor.val));
                          const pct = ((clamped - 0.1) / (1.5 - 0.1)) * 100;
                          return (
                            <div
                              key={anchor.label}
                              style={{
                                position: "absolute",
                                left: `${pct}%`,
                                top: 0,
                                transform: "translateX(-50%)",
                                display: "flex",
                                flexDirection: "column",
                                alignItems: "center",
                                cursor: "pointer",
                              }}
                              onClick={() => setKdeBandwidth(Math.round(clamped * 20) / 20)}
                            >
                              <InfoTooltip text={anchor.tip} width={220} position="below">
                                <div style={{ display: "flex", flexDirection: "column", alignItems: "center" }}>
                                  <div style={{
                                    width: 2, height: anchor.tickH,
                                    background: anchor.color, borderRadius: 1,
                                  }} />
                                  <span style={{
                                    fontSize: 8, color: anchor.color, fontWeight: 700,
                                    whiteSpace: "nowrap", marginTop: 1,
                                  }}>
                                    {anchor.label} ({anchor.val.toFixed(2)})
                                  </span>
                                </div>
                              </InfoTooltip>
                            </div>
                          );
                        })}
                      </div>
                    </div>
                  </div>
                )}
              </div>

              {/* Y-axis toggle: percentage vs raw count */}
              <div>
                <Label>Y-Axis</Label>
                <div style={{ display: "flex" }}>
                  <Btn active={usePercent} onClick={() => setUsePercent(true)} pos="left">%</Btn>
                  <Btn active={!usePercent} onClick={() => setUsePercent(false)} pos="right">#</Btn>
                </div>
              </div>

              {/* Bar color toggle: by dataset vs by Likert value */}
              <div>
                <Label>Bar Color</Label>
                <div style={{ display: "flex" }}>
                  <Btn active={!likertMode} onClick={() => setLikertMode(false)} pos="left">
                    Dataset
                  </Btn>
                  <Btn active={likertMode} onClick={() => setLikertMode(true)} pos="right">
                    Likert
                  </Btn>
                </div>
              </div>
            </>
          )}

          {/* Question label toggle: shown for means, delta, and categories views */}
          {view !== "grid" && (
            <div>
              <Label>Labels</Label>
              <div style={{ display: "flex" }}>
                <Btn active={!fullLabels} onClick={() => setFullLabels(false)} pos="left">
                  Short
                </Btn>
                <Btn active={fullLabels} onClick={() => setFullLabels(true)} pos="right">
                  Full
                </Btn>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* ---- LEGEND BAR ---- */}
      {view === "grid" && (
        <div style={{
          padding: "10px 24px", background: "#fff",
          borderBottom: "1px solid #e0e0e0",
          display: "flex", gap: 16, alignItems: "center", flexWrap: "wrap",
        }}>
          <span style={{ fontSize: 11, fontWeight: 600, color: "#888", textTransform: "uppercase" }}>
            X-Axis:
          </span>
          {DATA.likertScale.map((label, i) => (
            <span key={i} style={{ fontSize: 12, color: "#555", display: "flex", alignItems: "center", gap: 4 }}>
              <span style={{
                display: "inline-block", width: 12, height: 12, borderRadius: 2,
                background: likertMode ? LIKERT_COLORS[i] : "#ddd",
                border: "1px solid #ccc",
              }} />
              {LIKERT_SHORT[i]} = {label}
            </span>
          ))}
          {/* Show which fit method is active */}
          {fitMethod !== "none" && (
            <span style={{ fontSize: 11, color: "#888", marginLeft: 8, fontStyle: "italic" }}>
              Curve = {FIT_METHODS[fitMethod].label}
            </span>
          )}
        </div>
      )}

      {/* ---- CHART CONTENT ---- */}
      <div style={{ padding: "20px 24px" }}>
        {/* Empty state when no datasets selected */}
        {selected.length === 0 && (
          <div style={{ textAlign: "center", padding: 60, color: "#999", fontSize: 15 }}>
            Select at least one dataset above to see charts.
          </div>
        )}

        {/* Histogram grid view */}
        {view === "grid" && selected.length > 0 && (
          <div style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fill, minmax(360px, 1fr))",
            gap: 16,
          }}>
            {DATA.questions.map(q => (
              <div
                key={q}
                onClick={() => setModalQuestion(q)}
                style={{ cursor: "pointer" }}
              >
                <QuestionChart
                  question={q}
                  selectedDatasets={selected}
                  usePercent={usePercent}
                  likertMode={likertMode}
                  fitMethod={fitMethod}
                  kdeBandwidth={kdeBandwidth}
                  datasetList={effectiveDatasets}
                  colorList={effectiveColors}
                />
              </div>
            ))}
          </div>
        )}

        {/* Mean score comparison view */}
        {view === "means" && selected.length > 0 && (
          <MeanChart
            selectedDatasets={selected}
            datasetList={effectiveDatasets}
            colorList={effectiveColors}
            fullLabels={fullLabels}
          />
        )}

        {/* Delta comparison view */}
        {view === "delta" && selected.length > 0 && (
          <DeltaView
            selectedDatasets={selected}
            datasetList={effectiveDatasets}
            colorList={effectiveColors}
            fullLabels={fullLabels}
          />
        )}

        {/* Category grouping view */}
        {view === "categories" && selected.length > 0 && (
          <CategoryView
            selectedDatasets={selected}
            datasetList={effectiveDatasets}
            colorList={effectiveColors}
            fullLabels={fullLabels}
          />
        )}
      </div>

      {/* ---- EXPANDED CHART MODAL ---- */}
      {/* Clicking a chart in the grid opens it here at a larger size.
          Click the backdrop or press Escape to close. */}
      {modalQuestion && (
        <div
          onClick={() => setModalQuestion(null)}
          style={{
            position: "fixed",
            top: 0, left: 0, right: 0, bottom: 0,
            background: "rgba(0, 0, 0, 0.6)",
            zIndex: 200,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            padding: 24,
          }}
        >
          <div
            onClick={e => e.stopPropagation()}
            style={{
              background: "#fff",
              borderRadius: 12,
              boxShadow: "0 20px 60px rgba(0,0,0,0.3)",
              maxWidth: 900,
              width: "100%",
              maxHeight: "90vh",
              overflow: "auto",
              padding: "24px 28px",
              position: "relative",
            }}
          >
            {/* Close button */}
            <button
              onClick={() => setModalQuestion(null)}
              style={{
                position: "absolute", top: 12, right: 16,
                background: "none", border: "none",
                fontSize: 22, color: "#999", cursor: "pointer",
                lineHeight: 1, padding: 4,
              }}
            >
              ×
            </button>

            {/* Full question text */}
            <div style={{
              fontSize: 14, color: "#1a1a2e", fontWeight: 700,
              fontFamily: "'Source Serif 4', 'Georgia', serif",
              marginBottom: 4, paddingRight: 32, lineHeight: 1.4,
            }}>
              {modalQuestion}
            </div>
            {FULL_QUESTIONS[modalQuestion] && (
              <div style={{
                fontSize: 12, color: "#666", lineHeight: 1.5,
                marginBottom: 16, fontStyle: "italic",
              }}>
                "{FULL_QUESTIONS[modalQuestion]}"
              </div>
            )}

            {/* Large chart */}
            <QuestionChart
              question={modalQuestion}
              selectedDatasets={selected}
              usePercent={usePercent}
              likertMode={likertMode}
              fitMethod={fitMethod}
              kdeBandwidth={kdeBandwidth}
              datasetList={effectiveDatasets}
              colorList={effectiveColors}
              chartHeight={380}
            />
          </div>
        </div>
      )}

      {/* ---- FOOTER ---- */}
      <div style={{
        padding: "12px 24px 24px", fontSize: 11, color: "#999", textAlign: "center",
      }}>
        Data: InSight Program, Champlain College Career Collaborative.
        Likert mapped: Very untrue = -2, Somewhat untrue = -1, Neutral = 0,
        Somewhat true = +1, Very true = +2
      </div>
    </div>
  );
}